### ISSUE TITLE
btc-rpc-explorer fails to start

### ISSUE THREAD

**Issue by eleaner** [minibolt-guide/minibolt-gitbook#2]
After following the tutorial the btcrpcexplorer.service fails to start after reboot reporting inability to read the cookie file.
Manually restarted runs without problem
it feels like the service is starting too early (or that cookie file is created too late)

I managed to get around it with adding `Restart=always` to the `[Service]` section
I don't think it is the best solution but it works

reporting so it could be corrected in the tutorial

**Comment by twofaktor** [comment]
Services needs to be accommodated between them. Already on the roadmap. Thanks for your contribution!
